<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="5" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="34916" started-at="2021-05-10T08:44:50Z" finished-at="2021-05-10T08:45:25Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="34916" started-at="2021-05-10T08:44:50Z" finished-at="2021-05-10T08:45:25Z">
      <class name="Stepdefinition.DefectSD">
        <test-method status="PASS" signature="user_logged_in_successfully()[pri:1, instance:Stepdefinition.DefectSD@1dd02175]" name="user_logged_in_successfully" duration-ms="13576" started-at="2021-05-10T08:44:50Z" finished-at="2021-05-10T08:45:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- user_logged_in_successfully -->
        <test-method status="PASS" signature="user_clicked_on_item()[pri:2, instance:Stepdefinition.DefectSD@1dd02175]" name="user_clicked_on_item" duration-ms="9126" started-at="2021-05-10T08:45:03Z" finished-at="2021-05-10T08:45:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- user_clicked_on_item -->
        <test-method status="PASS" signature="grill_chart_should_be_displayed()[pri:3, instance:Stepdefinition.DefectSD@1dd02175]" name="grill_chart_should_be_displayed" duration-ms="3016" started-at="2021-05-10T08:45:12Z" finished-at="2021-05-10T08:45:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- grill_chart_should_be_displayed -->
        <test-method status="FAIL" signature="user_selected_two_items_under_same_section()[pri:4, instance:Stepdefinition.DefectSD@1dd02175]" name="user_selected_two_items_under_same_section" duration-ms="5891" started-at="2021-05-10T08:45:15Z" finished-at="2021-05-10T08:45:21Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[expected:<true> but was:<false>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: expected:<true> but was:<false>
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.failNotEquals(Assert.java:329)
at junit.framework.Assert.assertEquals(Assert.java:78)
at junit.framework.Assert.assertEquals(Assert.java:174)
at junit.framework.Assert.assertEquals(Assert.java:181)
at Stepdefinition.DefectSD.user_selected_two_items_under_same_section(DefectSD.java:64)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- user_selected_two_items_under_same_section -->
        <test-method status="PASS" signature="only_a_single_item_should_be_selected()[pri:5, instance:Stepdefinition.DefectSD@1dd02175]" name="only_a_single_item_should_be_selected" duration-ms="3213" started-at="2021-05-10T08:45:21Z" finished-at="2021-05-10T08:45:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- only_a_single_item_should_be_selected -->
      </class> <!-- Stepdefinition.DefectSD -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
